---

- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted

- name: Reload systemd daemon
  ansible.builtin.systemd:
    name: keepalived
    enabled: true
    daemon_reload: true
    state: restarted

- name: Restart systemd network
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted

- name: Keepalived-exporter restart
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    daemon_reload: true
    name: keepalived-exporter.service
