---

- name: restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted

- name: reload systemd daemon
  ansible.builtin.systemd:
    name: keepalived
    enabled: true
    daemon_reload: true
    state: restarted

- name: restart systemd network
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted

- name: keepalived-exporter restart
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    daemon_reload: true
    name: keepalived-exporter.service
